### ISSUE TITLE
未知的养成功能内存错误

### ISSUE THREAD

**Issue by PandoraZarna** [Taromati2/Taromati2#4]
**请确保你是在最新版本中遇见此问题**  
   昨天剛下也更新搂~

**确保你遇见的bug不是因为作弊引起的**
   No Cheat

**描述错误**  
   不知，内存错误?

**复现**  
  打最後的D級關卡結束後按"回去吧"

**预期行为**  
   回任務主頁領取錢錢

**截图**  
   ![image](https://user-images.githubusercontent.com/107383413/173449334-e4e66007-096b-4b2d-a161-4d81690eb54d.png)
   ![image](https://user-images.githubusercontent.com/107383413/173449432-276acc19-c96c-4c8a-b65e-274b0053b19b.png)

**附加上下文**  
```
内存错误
调用堆栈：
request
OnRequest
SHIORI_FW.RaiseIDEvent
OnChoiceSelectEx
Select.back
OpenRpgGameMenu
SubRpgGameMenu
信息参数
shiori.OnMemoryError
OnShioriMemoryError
```

**Comment by PandoraZarna** [comment]
不知不覺就提交issue了 應該是我設置上的問題

**Comment by PandoraZarna** [comment]
順便一提，剛打開養成系統的時候有些能力表有很奇妙的數字(魔法攻擊是461168601...等)，要重裝比較好嗎?

**Comment by steve02081504** [comment]
> 順便一提，剛打開養成系統的時候有些能力表有很奇妙的數字(魔法攻擊是461168601...等)，要重裝比較好嗎?

在调查中了，应该是我的问题。。

**Comment by steve02081504** [comment]
@PandoraZarna 
低数值时属性错乱问题已修复
有空时在线更新即可（不需要重装）

顺便问下，这个内存错误你能够稳定复现吗？
如果可以的话烦请对着橘花按`f8`然后将`shiori/aya_variable.cfg`发我

**Comment by PandoraZarna** [comment]
[aya_variable.zip](https://github.com/Taromati2/Taromati2/files/8901602/aya_variable.zip)
恩 成功複製3次。
試著把所有任務冒險區域都刷一遍就有了。我在D級任務區玩，從D農場刷到D核心，其中一個區域刷完要回家就會内存錯誤(核心回家，河谷回家，濕地回家)。出現錯誤回報後還可以繼續和橘花做其他事，但要按"任務"就會崩潰，SSP關閉。


内存错误
调用堆栈：
request
OnRequest
SHIORI_FW.RaiseIDEvent
OnChoiceSelectEx
Select.back
OpenRpgGameMenu
SubRpgGameMenu
信息参数
shiori.OnMemoryError
OnShioriMemoryError

**Comment by steve02081504** [comment]
辛苦了，明天我考一个试完了再找问题在哪

**Comment by PandoraZarna** [comment]
考試加油!

**Comment by steve02081504** [comment]
改主意了，刚熬夜调查完
这个bug修起来可能得花不少时间（涉及到yaya的未来600更新所作的底层修改导致的循环引用），所以我先做了一个小修补，不确定这个小修补会让问题变的更糟还是让问题更不容易出现。。希望是后者
等我这堆乱七八糟的期末考试搞完后再认真改，如果问题发展的更糟我会考虑回滚taromati2的yaya核心到500
谢谢你的报告

**Comment by PandoraZarna** [comment]
雖然可能幫不上忙 但之後也會繼續養橘花的! 加油歐!

**Comment by steve02081504** [comment]
已在此条提交中修复：https://github.com/Taromati2/yaya-shiori/commit/d906ff5a7d66f122096c60cae2580a2d8c61f180
如果相同的问题再次出现，请reopen这个issue
