### ISSUE TITLE
冒險模式裝備問題(小Bug)

### ISSUE THREAD

**Issue by PandoraZarna** [Taromati2/Taromati2#5]
**请确保你是在最新版本中遇见此问题**  
剛更新完成!

**确保你遇见的bug不是因为作弊引起的**
No Cheat

**描述错误**  
在商店買高級皮靴(DEF:90 ADF:1)會多出一雙忍者短布鞋(DEF:105 ADF:1), 無法出售但是可以裝備。

**复现**  
在冒險商店用25000金錢購買高級皮靴(LV60+)。

**预期行为**  
獲得一雙高級皮靴

**截图**  
![image](https://user-images.githubusercontent.com/107383413/174854505-b7f93c42-8efe-4976-95c0-50249679fa4a.png)
![image](https://user-images.githubusercontent.com/107383413/174854447-96e70aa9-2ae4-415e-a259-52fcb004badd.png)
![image](https://user-images.githubusercontent.com/107383413/174854585-51875436-74ac-44ea-9f36-974cda811276.png)
![image](https://user-images.githubusercontent.com/107383413/174855544-0345b570-f8cf-4a1d-ae00-877ab98e9de6.png)
![image](https://user-images.githubusercontent.com/107383413/174859414-50a22af0-0f58-4971-b740-225abc67d537.png)

**附加上下文**  
橘花現在一槍至少40000傷害了 怪物屍體排排睡
![image](https://user-images.githubusercontent.com/107383413/174855742-e0b13b41-3432-460e-8016-b24fccca9481.png)

**Comment by steve02081504** [comment]
绝赞熬夜补作业中
期末考完修

**Comment by PandoraZarna** [comment]
祝你武運 カッカ _(X3」∠)_

**Comment by steve02081504** [comment]
![图片](https://user-images.githubusercontent.com/31927825/175277517-9fd83624-24ec-495d-9f64-0abcd4bb3025.png)
草，我买不了

**Comment by steve02081504** [comment]
虽然我买不了但是我看了下代码应该没什么明显的问题。。
有没有可能是你打怪掉的鞋子，只是你一直没注意到？

**Comment by steve02081504** [comment]
已修复！
谢谢汇报XD
