### ISSUE TITLE
[BUG]内存错误

### ISSUE THREAD

**Issue by RenneXV** [Taromati2/Taromati2#6]
**请确保你是在最新版本中遇见此问题**  
**Make sure you have this bug in the latest release**  

**确保你遇见的bug不是因为作弊引起的**
**Make sure that bug are not caused by cheating**  
如果你遇见的bug由作弊引起，我将把你列在项目黑名单中  
If your bug caused by cheating, I'll block you  

**描述错误**  
内存错误

**复现**  
使用金钱购买好感度道具，会报错
重启后，养成系统重置成最初的模样

**截图**  
![图片](https://user-images.githubusercontent.com/31927825/184596898-04728652-bb1f-4f4f-87c8-2b9aae878b0a.png)

**附加上下文**  
```
request
OnRequest
SHIORI_FW.RaiseIDEvent
OnKikkaItem
OnKikkaItemList
KikkaStatus
KikkaVar
shiori.OnMemoryError
OnShioriMemoryError
```

**Comment by steve02081504** [comment]
有没有录屏和存档文件呢？
具体方法是对着橘花按f8，再找到ghost/master/shiori/aya_variable.cfg

**Comment by steve02081504** [comment]
可能的修复已实施
烦请更新一下再看看有没有效果

**Comment by steve02081504** [comment]
https://github.com/Taromati2/yaya-shiori/commit/1623b3ce087f773a9c5a6aefe12738322fc2bb1a
