### ISSUE TITLE
a bug，关于整点报时快速切换对话

### ISSUE THREAD

**Issue by rapuntseru** [Taromati2/Taromati2#7]
**请确保你是在最新版本中遇见此问题**  
**Make sure you have this bug in the latest release**  

**确保你遇见的bug不是因为作弊引起的**
**Make sure that bug are not caused by cheating**  
如果你遇见的bug由作弊引起，我将把你列在项目黑名单中  
If your bug caused by cheating, I'll block you  

**描述错误**  
**Describe the bug**  
对错误的清晰简明的描述于此  
一般要等一段时间不理橘花说的话的时候，橘花会说“不理橘花呢”，可是在整点报时的时候就快速的切换到下一句“不理我了”

**复现**  
**To Reproduce**  
你如何使用Taromati2  
How do you use Taromati2.  
平时挂着去干别的事

**预期行为**  
**Expected behavior**  
对你期望发生的事的清晰而简明的描述。  
希望整点报时之后不会快速切换

**截图**  
**Screenshots**  
如果适用，添加屏幕截图以帮助解释你的问题。  

**附加上下文**  
**Additional context**  
在此处添加有关该问题的任何其他上下文。

**Comment by steve02081504** [comment]
http://ssp.shillest.net/bts/view.php?id=561
根据ssp的bts，这是一个windows操作系统级别的bug
未来的ssp更新会在ssp层面缓解这个问题，但无法完全修复
我会在ssp更新后关闭这个issue

**Comment by steve02081504** [comment]
[SSP2.6.19](https://ponapalt.hatenablog.com/entry/2022/11/06/181014)
